/* ══════════════════════════════════════════════════════════════
   Doginal Dogs Legends — Rise of the Pack · Card Data
   ──────────────────────────────────────────────────────────────
   Pulled from the official gallery data at ddltcg.com.
   111 cards total. As of now, 12 are revealed and 99 show as
   "Revealing Soon" (sealed) — those fill in automatically as the
   official set reveals more. To refresh: re-pull their gallery
   data and regenerate this file.

   Card art & renders are hot-linked from ddltcg.com (their server).
   All card names, art, and game content © Doginal Dogs Legends.
   This companion is an independent fan tool, not affiliated with DDL.
   ══════════════════════════════════════════════════════════════ */

window.DDL_META = {
  setName: "Rise of the Pack",
  totalCards: 111,
  deckSize: 40,
  // Real classes from the official data:
  CLASSES: ["Bow", "Crown", "Pirate", "Wizard", "Zombie", "Neutral"],
  // Rarity tiers, rarest last:
  RARITIES: ["Common", "Uncommon", "Rare", "Epic"],
  // "Pill" on each card = its keyword ability:
  KEYWORDS: {
    "Play":    "Effect triggers when you play the card from hand.",
    "Haunt":   "Ongoing graveyard-style effect — read the card text.",
    "Passive": "Always on while this creature is in play."
  }
};

window.DDL_CARDS = [
  { id:"V001", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V002", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V003", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V004", name:"Gary", class:"Neutral", type:"Creature", cost:1, atk:1, hp:1, rarity:"Uncommon", tier:"Common/Rare", keyword:"Play", text:"Draw a card.", image:"https://ddltcg.com/card_renders/V004.png", sealed:false },
  { id:"V005", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V006", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V007", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V008", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V009", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V010", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V011", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V012", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V013", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V014", name:"Web", class:"Pirate", type:"Creature", cost:1, atk:2, hp:1, rarity:"Rare", tier:"Common/Rare", keyword:"Haunt", text:"Draw a card.", image:"https://ddltcg.com/card_renders/V014.png", sealed:false },
  { id:"V015", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V016", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V017", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V018", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V019", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V020", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V021", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V022", name:"Helios", class:"Crown", type:"Creature", cost:2, atk:0, hp:4, rarity:"Rare", tier:"Ultra Rare", keyword:"Passive", text:"At the start of your turn, deal 3 damage to the enemy Hero.", image:"https://ddltcg.com/card_renders/V022.png", sealed:false },
  { id:"V023", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V024", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V025", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V026", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V027", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V028", name:"Sunny", class:"Bow", type:"Creature", cost:2, atk:2, hp:3, rarity:"Uncommon", tier:"Common/Rare", keyword:"Passive", text:"When an adjacent Creature is destroyed, draw a card.", image:"https://ddltcg.com/card_renders/V028.png", sealed:false },
  { id:"V029", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V030", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V031", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V032", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V033", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V034", name:"Mary", class:"Bow", type:"Creature", cost:3, atk:3, hp:2, rarity:"Common", tier:"Common/Rare", keyword:"Play", text:"Deal 3 damage to a target.", image:"https://ddltcg.com/card_renders/V034.png", sealed:false },
  { id:"V035", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V036", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V037", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V038", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V039", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V040", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V041", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V042", name:"Sweetie", class:"Bow", type:"Creature", cost:3, atk:2, hp:2, rarity:"Common", tier:"Common/Rare", keyword:"Play", text:"Summon a Creature that costs 2 or less from your deck.", image:"https://ddltcg.com/card_renders/V042.png", sealed:false },
  { id:"V043", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V044", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V045", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V046", name:"Cherry", class:"Bow", type:"Creature", cost:4, atk:3, hp:3, rarity:"Rare", tier:"Common/Rare", keyword:"Play", text:"Summon a Creature that costs 2 or less from your deck.", image:"https://ddltcg.com/card_renders/V046.png", sealed:false },
  { id:"V047", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V048", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V049", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V050", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V051", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V052", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V053", name:"Seeker", class:"Crown", type:"Creature", cost:4, atk:4, hp:2, rarity:"Uncommon", tier:"Common/Rare", keyword:"Play", text:"Add a Creature from your deck to your hand.", image:"https://ddltcg.com/card_renders/V053.png", sealed:false },
  { id:"V054", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V055", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V056", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V057", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V058", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V059", name:"Toot", class:"Zombie", type:"Creature", cost:5, atk:4, hp:4, rarity:"Common", tier:"Ultra Rare", keyword:"Haunt", text:"Deal 5 damage to the enemy Hero.", image:"https://ddltcg.com/card_renders/V059.png", sealed:false },
  { id:"V060", name:"Volt", class:"Wizard", type:"Creature", cost:5, atk:5, hp:3, rarity:"Uncommon", tier:"Ultra Rare", keyword:"Play", text:"Add up to 2 Traps from your deck to your hand.", image:"https://ddltcg.com/card_renders/V060.png", sealed:false },
  { id:"V061", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V062", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V063", name:"Penny", class:"Pirate", type:"Creature", cost:6, atk:6, hp:2, rarity:"Epic", tier:"Ultra Rare", keyword:"Play", text:"Summon a Creature that costs 4 or less from your graveyard.", image:"https://ddltcg.com/card_renders/V063.png", sealed:false },
  { id:"V064", name:"Aria", class:"Bow", type:"Creature", cost:7, atk:7, hp:4, rarity:"Epic", tier:"Ultra Rare", keyword:"Play", text:"Deal 7 damage to a target.", image:"https://ddltcg.com/card_renders/V064.png", sealed:false },
  { id:"V065", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V066", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V067", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V068", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V069", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V070", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V071", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V072", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V073", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V074", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V075", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V076", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V077", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V078", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V079", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V080", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V081", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V082", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V083", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V084", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V085", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V086", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V087", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V088", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V089", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V090", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V091", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V092", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V093", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V094", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V095", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V096", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V097", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V098", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V099", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V100", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V101", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V102", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V103", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V104", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V105", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V106", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V107", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V108", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V109", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V110", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true },
  { id:"V111", name:"Revealing Soon", class:null, type:null, cost:null, atk:null, hp:null, rarity:null, tier:null, keyword:"", text:"", image:"", sealed:true }
];
